### ISSUE TITLE
_NMR_experiment_file.Name mandatoriness

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/nmr-star-dictionary#12]
Should there be an override that makes `_NMR_experiment_file.Name` mandatory when either a directory with type `Time-domain Data (raw spectral data)` has been uploaded, or when `_Experiment.Raw_data_flag` is set to `yes`?

**Comment by dmaziuk** [comment]
When Maria creates a metabolomics entry, it includes the index of NMR experiments (there are always 10). The index comes from the script driving the NMR spectrometer, the actual filenames are implicit because we always run on Bruker and we know how it names them. Furthermore we put them in at the directory level: 1, 2, etc., and don't list individual files inside. 

For your purposes you'll need a UI for entering this information. Possibly down to individual files inside subdirectories.

**Comment by jonwedell** [comment]
I believe this has been implemented a long time ago.
