### ISSUE TITLE
New conditional rule

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/nmr-star-dictionary#21]
Would it be reasonable to have a conditional rule making `_Experiment.NMR_spectrometer_label` mandatory if `_Experiment.Raw_data_flag` is `yes`? This would only apply on a per-row basis.

I can add the override rule, just checking the reasonableness of it.

**Comment by dmaziuk** [comment]
I think the problem is there is no `NMR_spectrometer_label`, there is a spectrometer list and spectrometer name drop-downs are populated from loop rows. In ADIT-NMR, that is.

There is some sort of post-cooking code that makes spectrometer and experiment saveframes from the lists, and then we turned off parts of it for some reason or other. So IIRC experiments are no longer expanded into saveframes but maybe spectrometers still are.

**Comment by dmaziuk** [comment]
(I don't think this is accessible from outside)
http://adit-alpha/cgi-bin/bmrb-adit/mk-top-interface-screen-view?ufid=2019-04-19.adit-alpha.80.2725570&blockid=NEED_ACC_NUM&context=deposit-en&dbname=&email=bmrbhelp@bmrb.wisc.edu&archdir=&expmeth=NMR&moltype=prot

-- you can/have to drill down to individual experiment section to list experiment_files, but htere are no individual spectrometer sections anymore (there used to be).

**Comment by jonwedell** [comment]
We changed the way this works - spectrometers are entered directly as saveframes, so no post-cooking is needed. (No more spectrometer list saveframe.) Therefore there are valid values to select for `NMR_spectrometer_label`.

<img width="1411" alt="Screen Shot 2019-04-19 at 2 36 39 PM" src="https://user-images.githubusercontent.com/5184895/56440899-a1cf6300-62b0-11e9-8ff0-8f0bdd2ddd1c.png">

**Comment by dmaziuk** [comment]
Oh, good, because in the current implementation half the `_Experiment` loops come in without an instrument filled in. I would make it mandatory regardless of `Raw_data_flag` if it were up to me.

Well except for those other instrument and experiment types we have in that table...

**Comment by jonwedell** [comment]
No conditional rule for now, it has been made always mandatory.
